language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: 7
        - php: hhvm-nightly

before_script:
    # Update composer
    - composer self-update

    # Install all dependecies
    - sh installall

    # Create MySQL database
    - mysql -e 'CREATE DATABASE benchmark;'

    # Download Employees Sample Database
    - wget https://launchpad.net/test-db/employees-db-1/1.0.6/+download/employees_db-full-1.0.6.tar.bz2

    # Extract data
    - tar -xjf employees_db-full-1.0.6.tar.bz2

    # Import to MySQL
    - cd employees_db
    - mysql -t < employees.sql
    - cd ../

script:
    - echo -e "First run (create cache files)" > first.log
    - sh testall > first.log | cat first.log

    - echo "Second run (using cache)" > second.log
    - sh testall > second.log | cat second.log

after_success:
    - git clone https://${GH_USER}:${GH_TOKEN}@github.com/${GH_REPO} git-logs

    - now=$(date +"%Y%m%d")
    - cat first.log >> git-logs/logs/${now}.log
    - echo -e "\n" >> git-logs/logs/${now}.log
    - cat second.log >> git-logs/logs/${now}.log
    - echo -e "\n\n" >> git-logs/logs/${now}.log

    - cd git-logs

    - git config --global user.name "${GH_USER_NAME}"
    - git config --global user.email "${GH_USER_EMAIL}"

    - git add logs/${now}.log
    - git commit -m "Update ${now}"

    - git push --all
